### ISSUE TITLE
library version mismatch 

### ISSUE THREAD

**Issue by nhannhinho** [Shreeshrii/tess5train-fonts#1]
Dear Shree,
I execute below command and got error.
I installed tesseract, and also compile from https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation.
which should be removed? or what is best way?
Thank you!

./1-makedata.sh

ERROR: shared library version mismatch (was 4.1.0-rc1-223-g3e71, expected 4.1.0-rc1-184-g497d
Did you use a wrong shared tesseract library?

$ tesseract --version
tesseract 4.1.0-rc1-223-g3e71
 leptonica-1.78.0
  libpng 1.6.34 : zlib 1.2.11
 Found SSE

**Comment by Shreeshrii** [comment]
You have 2 versions of tesseract. Try

make uninstall

**Comment by Shreeshrii** [comment]
Please post output of the following commands:

```
which tesseract
which text2image
which combine_lang_model
tesseract -v
text2image -v
combine_lang_model -v
tesseract --list-langs
text2image --help
combine_lang_model --help
```

**Comment by nhannhinho** [comment]
Dear Shree,
Thank you for your help.
I uninstalled all and also reinstalled one.
Now it works. I'm waiting for result.
Thanks

**Comment by Shreeshrii** [comment]
Thank you for your report. I have modified the wiki instructions and added:

https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation#build-with-training-tools
