### ISSUE TITLE
What is different between plus/minus training and just add new characters to the .training_text file?

### ISSUE THREAD

**Issue by ShroukMansour** [Shreeshrii/tess5train-fonts#10]
Hi @Shreeshrii , I have a question that I can't understand the difference between both. I need your illustration, please
More information, I will add the new characters (Arabic-Indic numbers) in the training_text file and finetune the ara.traineddata best file

**Comment by Shreeshrii** [comment]
finetune impact - old trainedadata and old unicharset. No new chars can be
added, even when they are in the training text.

finetune plus/minus - old traineddata to continue from and new unicharset.
A couple of new chars can be added by putting enough samples in training
text.

replace layer - old traineddata, new unicharset with multiple new
characters.

**Comment by ShroukMansour** [comment]
@Shreeshrii  , If I'm adding digits from 0-9 (Arabic-indic) Does this need to replace layer or plus-minus trainning is enough?
