### ISSUE TITLE
How to train using MNIST handwritten digits dataset?

### ISSUE THREAD

**Issue by irchamaji** [Shreeshrii/tess5train-fonts#13]
Hi,
I want to read handwritten digits from an image. There is MNIST handwritten digits dataset but I do not understand how to train it in Tesseract. Do you have any idea?
Thanks for advance

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesstrain/wiki

**Comment by Pranav1099** [comment]
@Ircham13 did you find the solution or have it documented somewhere
