### ISSUE TITLE
Different results between language-specific.sh and text2image command

### ISSUE THREAD

**Issue by PUYANG123** [Shreeshrii/tess5train-fonts#6]
language-specific.sh  show fonts kinds is different from the result of the command that text2image --fonts_dir /usr/share/fonts --list_available_fonts. why?

**Comment by Shreeshrii** [comment]
language-specific.sh shows list of fonts that were used at Google for training for tesseract 3.04.

The list for 4.0 is in okfonts.txt file in langdata_lstm

text2image --list_available_fonts shows the fonts that are installed on the system where the command is run.

**Comment by PUYANG123** [comment]
Hi,Shreeshrii:
      sorry,I still can't understand what you said, like this sentence that language-specific.sh shows list of fonts that were used at Google for training for tesseract 3.04. The list for 4.0 is in okfonts.txt file in langdata_lstm.

**Comment by PUYANG123** [comment]
Hi,Shreeshrii:
 what and where is the Okfont.txt file

**Comment by PUYANG123** [comment]
I find the font required for training less more than  the fonts that are installed on the system. why? How  can i modify the numbers of the fonts that are trained to be as many as the numbers of installed fonts?

**Comment by Shreeshrii** [comment]
Okfonts.txt is there in each language folder, specific to that language.

eg. https://github.com/tesseract-ocr/langdata_lstm/blob/master/chi_sim/okfonts.txt

This list could include commercial fonts also.

You can specify the fonts used for training when giving the tesstrain.sh command, eg.

```

 ~/tesseract/src/training/tesstrain.sh \
 --fonts_dir ~/.fonts \
 --training_text ~/langdata_lstm/chi_sim/chi_sim.training_text \
 --langdata_dir ~/langdata_lstm \
 --tessdata_dir ~/tesseract/tessdata \
 --lang chi_sim --linedata_only \
 --noextract_font_properties  \
 --exposures "0" \
 --maxpages 3 \
 --workspace_dir ~/tmp \
 --save_box_tiff \
 --fontlist  \
 "NSimSun" \
 "Arial Unicode MS" \
 "SimSun" \
 "Noto Sans CJK SC" \
 "Noto Sans Mono CJK SC" \
 --output_dir ~/tesstutorial/chi_sim_train
```

**Comment by Shreeshrii** [comment]
When Ray Smith at Google did the training, he used a large number of fonts so that all different types can be recognized with a single traineddata for a language.

When you do finetuning/training, you can choose to use fonts similar to the kind of images you want to OCR.
