### ISSUE TITLE
training tesseract

### ISSUE THREAD

**Issue by Bech007** [Shreeshrii/tess5train-fonts#7]
hello @Shreeshrii 
i have question about the result of training tesseract  plz can tel me what are these results and what does each value mean?
i'm beginner in tesseract train
 Mean rms=1.559%,
 delta=7.841%, 
char train=15.7%,
 word train=35.68%, 
skip ratio=0.1%,  
New best char error = 15.7
 Eval Char error rate=6.9447893,
 Word error rate=27.039255
 wrote best model:./SANLAYER/LAYER15.7_61423.checkpoint wrote checkpoint.
and thank you @Shreeshrii

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#iterations-and-checkpoints

and other related sections in wiki.

**Comment by Bech007** [comment]
thank you @Shreeshrii 
plz i have another question how i can generate the paire box-tiff form text file ?

**Comment by Bech007** [comment]
@Shreeshrii  any answer  plz?

**Comment by Shreeshrii** [comment]
tesstrain.sh script (text2image program) creates box/tiff pairs from
training text and fonts. Please see tesseract github  wiki page for details.
