### ISSUE TITLE
Extracting Neural Network Parameters

### ISSUE THREAD

**Issue by nscotto** [Shreeshrii/tess5train-fonts#8]
Is there a way to extract the neural network parameters from the traineddata?
I would like to recreate a tensorflow version of the model with the trained weights.

Kind Regards.

**Comment by Shreeshrii** [comment]
Please see
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files-in-tessdata_fast#version-string--40000alpha--network-specification-for-tessdata_fast

**Comment by nscotto** [comment]
Thank you.
I meant the trained weights, not only the specification.
